@startuml
'https://plantuml.com/class-diagram

object main
interface iAlpha {
    {abstract}work()
	{abstract}common()
}
abstract class alpha {
    i iAlpha
    name
    common()
}
note right of alpha::common
    i.work()
end note
class beta {
    alpha
    work()
}

main -> iAlpha: Uses >
iAlpha <--o alpha
alpha <|-- beta

@enduml