@startuml
'https://plantuml.com/class-diagram

object main
interface IFoo {
    {abstract}GetFooField()
	{abstract}SetFooField()
	{abstract}AbstractMethod()
}
abstract class Foo {
    IFoo
    fooField
    Method()
}
skinparam classAttributeIconSize 0
class xxFoo {
    *Foo
    xxFooField
    GetFooField()
	SetFooField()
	AbstractMethod()
}

main -> xxFoo: Uses >
IFoo <|.. Foo
IFoo <|.. xxFoo
Foo <|-- xxFoo

@enduml