@startuml
'https://plantuml.com/class-diagram

object main
interface DisplayIface {
    {abstract}Open()
	{abstract}Print()
	{abstract}Close()
}
abstract class Display {
    DisplayIface
    Display()
}
class CharDisplay {
    Open()
	Print()
	Close()
}
class StringDisplay {
    Open()
	Print()
	Close()
    printLine()
}

main -> Display: Uses >
Display *--> DisplayIface
DisplayIface <|.. CharDisplay
DisplayIface <|.. StringDisplay

@enduml