@startuml
'https://plantuml.com/sequence-diagram

participant "main" as main
participant ":Director" as dr

create ":TextBuilder" as tr
main -> tr: new
autoactivate on
main -> dr: Construct()
dr -> tr: MakeTitle()
return
dr -> tr: MakeString()
return
dr -> tr: MakeItems()
return
dr -> tr: Close()
return
return
main -> tr: GetResult()
return

@enduml