@startuml
'https://plantuml.com/class-diagram

object main
note left: GetFactory("ListFactory")
package 抽象工厂 {
    interface LinkImpl {
        {abstract}MakeHTML()
    }
    abstract class Link {
        LinkImpl
    }
    interface TrayImpl {
        {abstract}getTray()
        {abstract}setTray()
        {abstract}MakeHTML()
    }
    abstract class Tray {
        TrayImpl
        Add()
    }
    interface PageImpl {
        {abstract}getTitle()
        {abstract}getContent()
        {abstract}setContent()
        {abstract}MakeHTML()
    }
    abstract class Page {
        PageImpl
        Add()
        Output()
    }
    interface Factory {
        CreateLink()
        CreateTray()
        CreatePage()
    }
}
package 具体工厂 {
    class ListLink {
        caption
        url
        MakeHTML()
    }
    class ListTray {
        caption
        tray
        getTray()
        setTray()
        MakeHTML()
    }
    class ListPage {
        title
        author
        content
        getTitle()
        getContent()
        setContent()
        MakeHTML()
    }
    class ListFactory {
        CreateLink()
        CreateTray()
        CreatePage()
    }
}

LinkImpl <--* Link
TrayImpl <--* Tray
PageImpl <--* Page
Link <-- Factory: Creates <
Tray <-- Factory: Creates <
Page <-- Factory: Creates <
Factory <-- main: Uses <
LinkImpl <|.. ListLink
TrayImpl <|.. ListTray
PageImpl <|.. ListPage
ListLink <-- ListFactory: Creates <
ListTray <-- ListFactory: Creates <
ListPage <-- ListFactory: Creates <
Factory <|.. ListFactory 

@enduml