@startuml
'https://plantuml.com/class-diagram

package factory {
    interface ILink {
        MakeHTML()
    }
    abstract class Link {
        ILink
    }
    interface ITray {
        getTray()
        setTray()
        MakeHTML()
    }
    abstract class Tray {
        ITray
        Add()
    }
    interface IPage {
        getTitle()
        getContent()
        setContent()
        MakeHTML()
    }
    abstract class Page {
        IPage
        Add()
        Output()
    }
    interface Factory {
        CreateLink()
        CreateTray()
        CreatePage()
    }
}
package listfactory {
    class ListLink {
        caption
        url
        MakeHTML()
    }
    class ListTray {
        caption
        tray
        getTray()
        setTray()
        MakeHTML()
    }
    class ListPage {
        title
        author
        content
        getTitle()
        getContent()
        setContent()
        MakeHTML()
    }
    class ListFactory {
        CreateLink()
        CreateTray()
        CreatePage()
    }
}

ILink <--o Link
ITray <--o Tray
IPage <--o Page
Link <-- Factory: Creates <
Tray <-- Factory: Creates <
Page <-- Factory: Creates <
ILink <|.. ListLink
ITray <|.. ListTray
IPage <|.. ListPage
ListLink <-- ListFactory: Creates <
ListTray <-- ListFactory: Creates <
ListPage <-- ListFactory: Creates <
Factory <|.. ListFactory 

@enduml