@startuml
'https://plantuml.com/class-diagram

interface Aggregate {
    {abstract}Iterator()
}
interface Iterator {
    {abstract}HasNext()
    {abstract}Next()
}
class Book {
    name
    GetName()
}
class BookShelf {
    books []*Book
    last
    GetBookAt()
    AppendBook()
    GetLength()
    Iterator()
}
class BookShelfIterator {
    bookShelf *BookShelf
    index
    HasNext()
    Next()
}

Aggregate -> Iterator: Creates >
Aggregate <|.. BookShelf
Iterator <|.. BookShelfIterator
BookShelf <-o BookShelfIterator
BookShelf o--> Book

@enduml