@startuml
'https://plantuml.com/sequence-diagram

participant main
participant alice
participant bob
participant charlie
participant diana
participant elmo
participant fred

autoactivate on
main -> alice: Support()
alice -> bob: Support()
bob -> charlie: Support()
charlie -> diana: Support()
diana -> elmo: Support()
return
return
return
return
return


@enduml